[package]
name = "SilentHillRustomizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
rfd = "0.8.2"
windows = "0.38.0"
process-memory = "0.4.0"